from __future__ import annotations

import csv
from dataclasses import asdict
from io import StringIO
import json
from pathlib import Path
import shutil

from .model import Blueprint, Network


GENERATED_MARKER = "Generated by NetForge IaC. Do not edit by hand."


def _slug(value: str) -> str:
    return "".join(character.lower() if character.isalnum() else "-" for character in value).strip("-")


def _networkd_netdev(network: Network) -> str:
    return (
        f"# {GENERATED_MARKER}\n"
        "[NetDev]\n"
        f"Name=vlan{network.vlan_id}\n"
        "Kind=vlan\n\n"
        "[VLAN]\n"
        f"Id={network.vlan_id}\n"
    )


def _networkd_vlan_network(network: Network) -> str:
    return (
        f"# {GENERATED_MARKER}\n"
        "[Match]\n"
        f"Name=vlan{network.vlan_id}\n\n"
        "[Network]\n"
        f"Address={network.gateway}/{network.subnet.prefixlen}\n"
        "ConfigureWithoutCarrier=yes\n"
        "IPForward=yes\n"
    )


def _networkd_trunk(blueprint: Blueprint) -> str:
    vlan_lines = "".join(f"VLAN=vlan{network.vlan_id}\n" for network in sorted(blueprint.networks, key=lambda item: item.vlan_id))
    return (
        f"# {GENERATED_MARKER}\n"
        "[Match]\n"
        f"Name={blueprint.site.trunk_interface}\n\n"
        "[Network]\n"
        "LinkLocalAddressing=no\n"
        f"{vlan_lines}"
    )


def _dnsmasq(blueprint: Blueprint) -> str:
    lines = [f"# {GENERATED_MARKER}", f"domain={blueprint.site.domain}", "expand-hosts", ""]
    for network in sorted(blueprint.networks, key=lambda item: item.vlan_id):
        if not network.dhcp_enabled:
            continue
        tag = _slug(network.name)
        dns = ",".join(str(item) for item in network.dns_servers)
        lines.extend([
            f"# VLAN {network.vlan_id} - {network.name}",
            f"interface=vlan{network.vlan_id}",
            f"dhcp-range=set:{tag},{network.dhcp_start},{network.dhcp_end},{network.subnet.netmask},{blueprint.site.dhcp_lease}",
            f"dhcp-option=tag:{tag},option:router,{network.gateway}",
            f"dhcp-option=tag:{tag},option:dns-server,{dns}",
            "",
        ])
    for host in sorted(blueprint.hosts, key=lambda item: (item.network.casefold(), int(item.address))):
        lines.append(f"dhcp-host={host.mac},{host.address},{host.name}")
    lines.append("")
    return "\n".join(lines)


def _markdown_plan(blueprint: Blueprint) -> str:
    lines = [
        f"# Network plan: {blueprint.site.name}",
        "",
        f"> {GENERATED_MARKER}",
        "",
        f"Domain: `{blueprint.site.domain}`  ",
        f"Router trunk interface: `{blueprint.site.trunk_interface}`",
        "",
        "## VLANs and subnets",
        "",
        "| VLAN | Name | Subnet | Gateway | DHCP pool | DNS | Description |",
        "|---:|---|---|---|---|---|---|",
    ]
    for network in sorted(blueprint.networks, key=lambda item: item.vlan_id):
        dhcp = f"{network.dhcp_start}–{network.dhcp_end}" if network.dhcp_enabled else "Disabled"
        dns = ", ".join(str(item) for item in network.dns_servers)
        lines.append(
            f"| {network.vlan_id} | {network.name} | `{network.subnet}` | `{network.gateway}` | "
            f"{dhcp} | {dns} | {network.description or '-'} |"
        )

    lines.extend(["", "## Static hosts", "", "| Host | Network | Address | MAC | Description |", "|---|---|---|---|---|"])
    if blueprint.hosts:
        for host in sorted(blueprint.hosts, key=lambda item: (item.network.casefold(), int(item.address))):
            lines.append(f"| {host.name} | {host.network} | `{host.address}` | `{host.mac}` | {host.description or '-'} |")
    else:
        lines.append("| _No static hosts defined_ | | | | |")

    lines.extend([
        "",
        "## Deployment order",
        "",
        "1. Review this plan and commit the source TOML file.",
        "2. Configure the VLANs on the switch trunk and access ports.",
        "3. Apply the generated systemd-networkd files on the Linux router only after an out-of-band access path is available.",
        "4. Validate routing and firewall policy before enabling DHCP.",
        "5. Apply the dnsmasq file and test one client per VLAN.",
        "",
        "The generated files intentionally do not create firewall allow rules. Segmentation policy should be explicit and reviewed separately.",
        "",
    ])
    return "\n".join(lines)


def _write_csv(rows: list[list[str]]) -> str:
    output = StringIO()
    writer = csv.writer(output, lineterminator="\n")
    writer.writerows(rows)
    return output.getvalue()


def generate(blueprint: Blueprint, output_dir: Path, clean: bool = False) -> list[Path]:
    if clean and output_dir.exists():
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    files: dict[Path, str] = {}
    files[output_dir / "README.md"] = _markdown_plan(blueprint)
    files[output_dir / "dnsmasq" / "vlans.conf"] = _dnsmasq(blueprint)
    files[output_dir / "systemd-networkd" / "10-trunk.network"] = _networkd_trunk(blueprint)

    for network in blueprint.networks:
        prefix = f"20-vlan{network.vlan_id}"
        files[output_dir / "systemd-networkd" / f"{prefix}.netdev"] = _networkd_netdev(network)
        files[output_dir / "systemd-networkd" / f"{prefix}.network"] = _networkd_vlan_network(network)

    alias_rows = [["alias", "type", "value", "description"]]
    for network in sorted(blueprint.networks, key=lambda item: item.vlan_id):
        alias_rows.append([
            f"NET_{network.name.upper().replace('-', '_')}",
            "network",
            str(network.subnet),
            network.description,
        ])
    files[output_dir / "firewall" / "aliases.csv"] = _write_csv(alias_rows)

    host_rows = [["name", "network", "address", "mac", "description"]]
    for host in sorted(blueprint.hosts, key=lambda item: item.name.casefold()):
        host_rows.append([host.name, host.network, str(host.address), host.mac, host.description])
    files[output_dir / "inventory" / "hosts.csv"] = _write_csv(host_rows)

    normalized = {
        "site": asdict(blueprint.site),
        "networks": [
            {
                **asdict(network),
                "subnet": str(network.subnet),
                "gateway": str(network.gateway),
                "dhcp_start": str(network.dhcp_start) if network.dhcp_start else None,
                "dhcp_end": str(network.dhcp_end) if network.dhcp_end else None,
                "dns_servers": [str(item) for item in network.dns_servers],
            }
            for network in blueprint.networks
        ],
        "hosts": [
            {**asdict(host), "address": str(host.address)} for host in blueprint.hosts
        ],
    }
    files[output_dir / "inventory" / "blueprint.json"] = json.dumps(normalized, indent=2) + "\n"

    written: list[Path] = []
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        written.append(path)
    return sorted(written)
